// apps/angular-app/src/app/app.ts
import { Component, signal, effect, onDestroy } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { createGunsoleClient } from 'gunsole-js';

const gunsole = createGunsoleClient({
  projectId: 'test-project-angular',
  apiKey: 'test-api-key',
  mode: 'local',
  env: 'development',
  appName: 'Angular App',
  appVersion: '1.0.0',
  defaultTags: { framework: 'angular' },
});

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, FormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App implements onDestroy {
  protected readonly count = signal(0);
  protected readonly userId = signal('user-123');
  protected readonly sessionId = signal('session-abc');

  constructor() {
    effect(() => {
      gunsole.setUser({ id: this.userId(), email: 'user@example.com' });
      gunsole.setSessionId(this.sessionId());
    });

    gunsole.attachGlobalErrorHandlers();

    gunsole.log({
      level: 'info',
      bucket: 'app_lifecycle',
      message: 'App initialized',
      context: { framework: 'angular' },
    });
  }

  ngOnDestroy(): void {
    gunsole.detachGlobalErrorHandlers();
    gunsole.flush();
  }

  protected handleLog(level: 'info' | 'debug' | 'warn' | 'error'): void {
    gunsole.log({
      level,
      bucket: 'user_action',
      message: `User clicked ${level} log button`,
      context: { count: this.count(), timestamp: Date.now() },
      tags: { action: 'button_click', level },
    });
  }

  protected handleIncrement(): void {
    const newCount = this.count() + 1;
    this.count.set(newCount);
    gunsole.log({
      level: 'info',
      bucket: 'counter',
      message: 'Counter incremented',
      context: { count: newCount },
    });
  }

  protected handleError(): void {
    gunsole.log({
      level: 'error',
      bucket: 'test_error',
      message: 'Test error logged',
      context: { error: 'This is a test error', stack: 'test stack' },
    });
  }

  protected async handleFlush(): Promise<void> {
    await gunsole.flush();
    alert('Logs flushed!');
  }
}

// apps/react-vite/src/App.tsx
import { useState, useEffect } from "react";
import { createGunsoleClient } from "gunsole-js";
import "./App.css";

const gunsole = createGunsoleClient({
  projectId: "test-project-react",
  apiKey: "test-api-key",
  mode: "local",
  env: "development",
  appName: "React Vite App",
  appVersion: "1.0.0",
  defaultTags: { framework: "react", bundler: "vite" },
});

function App() {
  const [count, setCount] = useState(0);
  const [userId, setUserId] = useState("user-123");
  const [sessionId, setSessionId] = useState("session-abc");

  useEffect(() => {
    gunsole.setUser({ id: userId, email: "user@example.com" });
    gunsole.setSessionId(sessionId);
    gunsole.attachGlobalErrorHandlers();

    gunsole.log({
      level: "info",
      bucket: "app_lifecycle",
      message: "App mounted",
      context: { framework: "react" },
    });

    return () => {
      gunsole.detachGlobalErrorHandlers();
      gunsole.flush();
    };
  }, [userId, sessionId]);

  const handleLog = (level: "info" | "debug" | "warn" | "error") => {
    gunsole.log({
      level,
      bucket: "user_action",
      message: `User clicked ${level} log button`,
      context: { count, timestamp: Date.now() },
      tags: { action: "button_click", level },
    });
  };

  const handleIncrement = () => {
    const newCount = count + 1;
    setCount(newCount);
    gunsole.log({
      level: "info",
      bucket: "counter",
      message: "Counter incremented",
      context: { count: newCount },
    });
  };

  const handleError = () => {
    gunsole.log({
      level: "error",
      bucket: "test_error",
      message: "Test error logged",
      context: { error: "This is a test error", stack: "test stack" },
    });
  };

  const handleFlush = async () => {
    await gunsole.flush();
    alert("Logs flushed!");
  };

  return (
    <div className="app">
      <h1>Gunsole JS - React + Vite Test</h1>
      <div className="card">
        <div className="section">
          <h2>Counter: {count}</h2>
          <button onClick={handleIncrement}>Increment</button>
        </div>

        <div className="section">
          <h2>Log Actions</h2>
          <div className="button-group">
            <button onClick={() => handleLog("info")}>Log Info</button>
            <button onClick={() => handleLog("debug")}>Log Debug</button>
            <button onClick={() => handleLog("warn")}>Log Warn</button>
            <button onClick={() => handleLog("error")}>Log Error</button>
          </div>
        </div>

        <div className="section">
          <h2>User & Session</h2>
          <div className="input-group">
            <label>
              User ID:
              <input
                type="text"
                value={userId}
                onChange={(e) => setUserId(e.target.value)}
              />
            </label>
            <label>
              Session ID:
              <input
                type="text"
                value={sessionId}
                onChange={(e) => setSessionId(e.target.value)}
              />
            </label>
          </div>
        </div>

        <div className="section">
          <h2>Actions</h2>
          <div className="button-group">
            <button onClick={handleError}>Trigger Error Log</button>
            <button onClick={handleFlush}>Flush Logs</button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
